In [2]:
import pandas as pd
df=pd.read_csv('survey_results_public.csv')
ex=pd.read_csv('pyt.csv',';')
df=pd.read_excel('plik.xlsx', sheet_name="rejestr_zakodowany")
df.set_index('Respondent', inplace=True)
df
empty = pd.DataFrame(columns=['name','age','gender'])
empty=empty.append({'name':"jan",'age':100, 'gender':'m'}, ignore_index=True)
empty=empty.append({'gender':'m'}, ignore_index=True)
empty=empty.append({'name':"fran",'age':300,'gender':'m',}, ignore_index=True)
df3.loc[war,'wiek_slownie']='piecdziesiat'

res=pd.Series([10,20,30])
cars={'audi':'a4','bmw':'x5'}
res2=pd.Series(cars)
frame={'name':["luwy",'Kuba'],
       'club':['Bay',np.NaN],
       'age':[32,np.NaN]
      }
tab=['sty','lut','mar']
seria=pd.Series(tab)
df=pd.DataFrame(frame)
df['ser']=seria

In [ ]:
import pandas as pd
con=pd.Series(['Poland', 'france','poland','France','9ard'])
for k,v in wyn.iteritems():
    con[k]
    
for k,v in df.iterrows():
    if (v['brk']=='10_C10_S951_XK') & (v['bs']>2):
        df.loc[k,'nowa']='war1'

In [ ]:
import pandas as pd

countries=['Poland','Germany']
war2=df["Country"].isin(countries)
war=df['LanguageWorkedWith'].str.contains("Python")==True
con=pd.Series(['Poland', 'france','poland','France','9ard'])
wyn=con.str.match("([a-z])")

In [ ]:
import numpy as np
import pandas as pd

agregat=df.groupby(['s1a','s1b','s1c'])
agregat['regon'].count()
df['age'].isnull().sum()


#df['name'].str.count(pat="(^[A-Z][a-z]{3})")

In [3]:
df=pd.read_csv('survey_results_public.csv')
pd.set_option('max_columns', None)
res=df.Age.value_counts().to_frame().reset_index()
bi=pd.cut(res['index'],bins=[1,20,40,60], labels=['l','st','bst'])
res['prze']=bi
res

     index   Age prze
0     25.0  2693   st
1     28.0  2412   st
2     30.0  2406   st
3     26.0  2391   st
4     27.0  2338   st
..     ...   ...  ...
105   26.8     1   st
106    3.0     1    l
107   14.7     1    l
108   26.5     1   st
109   22.5     1   st

[110 rows x 3 columns]